# -*- coding: utf-8 -*-
"""Expand BTEC Business unit quiz.json files with 200+ additional MCQs.
Appends MCQs with sequential ids after the existing max id per unit.
"""
import json, os

ROOT = r"c:\Users\mistr\OneDrive\Documents\GitHub\ra10\revision\btec\level-3\business"

def mcq(i, aim, topic, q, choices, correct, expl, typ="mcq"):
    return {"id": "Q%03d" % i, "learning_aim": aim, "topic": topic, "type": typ,
            "question": q, "choices": choices, "correct_index": correct, "explanation": expl}

def load(unit):
    p = os.path.join(ROOT, unit, "data", "quiz.json")
    with open(p, encoding="utf-8") as f:
        return json.load(f)

def save(unit, data):
    p = os.path.join(ROOT, unit, "data", "quiz.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

def next_num(data):
    mx = 0
    for it in data:
        s = str(it.get("id", ""))
        if s.startswith("Q"):
            try:
                mx = max(mx, int(s[1:]))
            except ValueError:
                pass
    return mx

# ===================== UNIT 1 =====================
U1 = [
 # A — ownership & liability
 ("A","Ownership","Which type of business ownership has a separate legal identity from its owners?",
  ["Sole trader","Partnership","Private limited company","Cooperatives"],2,"An Ltd (and plc) is a separate legal entity, unlike sole traders and partnerships."),
 ("A","Ownership","For which business type are owners personally responsible for all debts?",
  ["Private limited company","Public limited company","Sole trader","Franchise"],2,"Sole traders and (ordinary) partners have unlimited liability."),
 ("A","Ownership","Who owns a public limited company (plc)?",
  ["The government","Shareholders","Managers only","Employees"],1,"A plc is owned by its shareholders, who buy shares on the stock exchange."),
 ("A","Ownership","Which business type cannot sell shares to the general public?",
  ["Public limited company","Private limited company (Ltd)","Neither","Both"],1,"Only a plc can sell shares to the public; an Ltd sells shares privately."),
 ("A","Ownership","What is the main advantage of limited liability to owners?",
  ["Higher profits guaranteed","Their personal assets are protected","No tax to pay","They get more control"],1,"Limited liability means owners only risk what they invested."),
 ("A","Sectors","A mining company extracting iron ore operates in which sector?",
  ["Primary","Secondary","Tertiary","Quaternary"],0,"Extracting raw materials is the primary sector."),
 ("A","Sectors","A software company providing IT support operates in which sector?",
  ["Primary","Secondary","Tertiary","Quaternary"],3,"IT and information services are the quaternary sector."),
 ("A","Sectors","A restaurant preparing and serving food is part of which sector?",
  ["Primary","Secondary","Tertiary","Quaternary"],2,"Providing a service is the tertiary sector."),
 ("A","Size","A business with 10–49 employees is classified as:",
  ["Micro","Small","Medium","Large"],1,"Small businesses have 10–49 staff."),
 ("A","Size","A business with 50–249 employees is classified as:",
  ["Micro","Small","Medium","Large"],2,"Medium businesses have 50–249 staff."),
 ("A","Size","Which measure is NOT used to classify business size?",
  ["Number of employees","Turnover","Market share of premises colour","Value of assets"],2,"Size is measured by employees, turnover, assets/capital, not colour."),
 ("A","Scope","A business selling in one town only has which scope?",
  ["Local","National","International","Global"],0,"Operating within a small area is local scope."),
 ("A","Scope","A business operating in several countries has which scope?",
  ["Local","National","International","Only domestic"],2,"Operating across more than one country is international scope."),
 ("A","Success","Which is a key reason for business success?",
  ["Avoiding innovation","Clear vision and leadership","High staff turnover","Ignoring customers"],1,"Clear vision and leadership give direction and motivation."),
 ("A","Success","Which is most likely to lead to business failure?",
  ["Strong cash flow","Innovative products","Poor cash management","Customer loyalty"],2,"Poor cash management is a common cause of business failure."),
 ("A","Stakeholders","Which is an internal stakeholder?",
  ["Supplier","Customer","Manager","Government"],2,"Managers are internal; suppliers, customers and government are external."),
 ("A","Stakeholders","Which is an external stakeholder?",
  ["Owner","Employee","Manager","Local community"],3,"The local community is external to the business."),
 ("A","Stakeholders","How can customers influence a business?",
  ["By setting tax rates","By choosing whether to buy","By appointing managers","By writing laws"],1,"Customer purchasing decisions directly affect revenue."),
 ("A","Communication","Which is a form of written communication?",
  ["Face-to-face meeting","Business letter","Video conference","Telephone call"],1,"A business letter is written communication."),
 ("A","Communication","Video conferencing is a form of:",
  ["Written communication","Oral communication","No communication","Financial statement"],1,"Video conferencing is a spoken/oral method."),
 ("A","Communication","Which is a benefit of effective communication?",
  ["More errors","Reduced coordination","Better customer relationships","Slower decisions"],2,"Good communication builds trust with customers."),
 # B — structure & organisation
 ("B","Structure","Which structure has many layers and a clear chain of command?",
  ["Flat","Matrix","Hierarchical","Holacratic"],2,"Hierarchical structures have many layers."),
 ("B","Structure","Which structure has few layers and wide spans of control?",
  ["Hierarchical","Flat","Tall","Tall"],1,"Flat structures have few layers and wide spans of control."),
 ("B","Structure","In a matrix structure, an employee reports to:",
  ["No one","One manager","More than one manager","Only shareholders"],2,"Matrix structures combine functional and project reporting."),
 ("B","Structure","Which structure removes formal management hierarchy?",
  ["Hierarchical","Flat","Holacratic","Tall"],2,"Holacratic structures distribute authority to self-managing teams."),
 ("B","Functions","Which function recruits and trains staff?",
  ["Marketing","Finance","Human resources","Production"],2,"HR handles recruitment and training."),
 ("B","Functions","Which function manages the budget and accounts?",
  ["HR","Finance","Sales","Customer service"],1,"Finance manages money, budgets and accounts."),
 ("B","Functions","Which function promotes products to customers?",
  ["Marketing","Production","Purchasing","Finance"],0,"Marketing promotes products and manages the brand."),
 ("B","Functions","Which function transforms inputs into goods?",
  ["Sales","Production/operations","HR","Finance"],1,"Production/operations converts inputs into outputs."),
 ("B","Aims","Which is a typical aim of a private sector business?",
  ["Value for money","Profit maximisation","Free service","Break even never"],1,"Private businesses typically aim to maximise profit."),
 ("B","Aims","Which is a typical aim of a public sector organisation?",
  ["Profit maximisation","Providing a quality service","Market leadership","Growth only"],1,"Public sector aims to provide services and value for money."),
 ("B","Aims","Which is a typical aim of a not-for-profit organisation?",
  ["Maximising profit","Alleviating a social problem","Growth at all costs","Shareholder returns"],1,"Not-for-profits pursue social aims."),
 ("B","SMART","In SMART objectives, the 'S' stands for:",
  ["Simple","Specific","Speedy","Selfish"],1,"S = Specific."),
 ("B","SMART","A SMART objective should be:",
  ["Vague","Time-constrained","Impossible","Irrelevant"],1,"SMART objectives are time-bound/constrained."),
 ("B","SMART","'To increase market share' is not SMART because it is not:",
  ["Measurable","Positive","Long-term","Written"],0,"It lacks a measurable amount and a timeframe."),
 # C — environment
 ("C","PESTLE","Rising interest rates are which PESTLE factor?",
  ["Social","Economic","Political","Legal"],1,"Interest rates are an economic factor."),
 ("C","PESTLE","New employment laws are which PESTLE factor?",
  ["Economic","Social","Legal","Environmental"],2,"Laws are legal factors."),
 ("C","PESTLE","An ageing population is which PESTLE factor?",
  ["Political","Economic","Social","Technological"],2,"Demographics are a social factor."),
 ("C","PESTLE","New automation technology is which PESTLE factor?",
  ["Social","Technological","Legal","Economic"],1,"Technology is a technological factor."),
 ("C","CSR","Corporate social responsibility means:",
  ["Maximising profit at any cost","Acting ethically and considering social/environmental impact","Avoiding all regulation","Reducing quality"],1,"CSR is acting ethically beyond legal requirements."),
 ("C","CSR","Which is an example of CSR?",
  ["Increasing prices","Reducing carbon emissions","Cutting staff pay","Polluting rivers"],1,"Reducing emissions is a socially responsible action."),
 ("C","Competition","Which gives a competitive advantage?",
  ["Higher costs","Unique differentiation","Worse service","Slower delivery"],1,"Differentiation creates a competitive advantage."),
 ("C","Competition","Cost leadership means:",
  ["Being the most expensive","Being the lowest-cost producer","Buying the most stock","Hiring the most staff"],1,"Cost leadership = lowest cost producer."),
 ("C","SWOT","In SWOT, Strengths and Weaknesses are:",
  ["External factors","Internal factors","Irrelevant","Only financial"],1,"Strengths and Weaknesses are internal."),
 ("C","SWOT","In SWOT, Opportunities and Threats are:",
  ["Internal factors","External factors","Only legal","Controllable"],1,"Opportunities and Threats are external."),
 ("C","Analysis","PESTLE analysis examines:",
  ["Only competitors","The external environment","Only finances","Only marketing"],1,"PESTLE analyses the external environment."),
 ("C","Analysis","Porter's Five Forces analyses:",
  ["The competitive environment","Only pricing","Only marketing","Only finance"],0,"Five Forces analyses the competitive environment."),
 # D — markets
 ("D","Market structure","Perfect competition features:",
  ["One dominant firm","Many firms, identical products","High barriers","Differentiated products"],1,"Perfect competition: many firms, homogeneous products."),
 ("D","Market structure","A monopoly is:",
  ["Perfect competition","One dominant firm","Many small firms","A cooperative"],1,"A monopoly has one dominant firm."),
 ("D","Market structure","An oligopoly features:",
  ["Many tiny firms","A few large firms","One firm","No competition"],1,"Oligopoly = a few large firms dominate."),
 ("D","Demand","Which increases demand?",
  ["Rising price","Falling income","Successful advertising","Fewer substitutes"],2,"Advertising stimulates demand."),
 ("D","Demand","Which factor influences demand?",
  ["Availability of raw materials","Consumer income","Logistics","Labour availability"],1,"Income is a demand-factor."),
 ("D","Supply","Which factor influences supply?",
  ["Consumer tastes","Availability of raw materials","Consumer income","Advertising"],1,"Raw material availability affects supply."),
 ("D","Supply","Higher raw material costs are likely to:",
  ["Increase supply","Reduce supply","Not affect supply","Increase demand"],1,"Higher input costs reduce supply."),
 ("D","Elasticity","Price elastic demand means quantity demanded:",
  ["Changes proportionally more than price","Barely changes with price","Never changes","Equals zero"],0,"Elastic: Qd changes more than proportionally to price."),
 ("D","Elasticity","Price inelastic demand means quantity demanded:",
  ["Changes a lot","Changes proportionally less than price","Equals price","Is infinite"],1,"Inelastic: Qd changes less than proportionally to price."),
 ("D","Elasticity","Demand for necessities is usually:",
  ["Elastic","Inelastic","Perfectly elastic","Zero"],1,"Necessities have inelastic demand."),
 ("D","Elasticity","Demand for luxury goods is usually:",
  ["Inelastic","Elastic","Perfectly inelastic","Fixed"],1,"Luxuries have elastic demand."),
 ("D","Pricing","In perfect competition, firms are:",
  ["Price makers","Price takers","Monopolies","Price setters only"],1,"Firms in perfect competition are price takers."),
 ("D","Pricing","A price war is:",
  ["Firms repeatedly cutting prices","Firms agreeing prices","A government tax","An advertising campaign"],0,"A price war is repeated price cutting."),
 ("D","Pricing","A business responding to a rival's price cut by differentiating is using:",
  ["Price competition","Non-price competition","Monopoly power","Cost-plus pricing"],1,"Differentiation is non-price competition."),
 # E — innovation & enterprise
 ("E","Innovation","Innovation means:",
  ["Copying rivals","Successfully exploiting new ideas","Reducing staff","Cutting prices"],1,"Innovation is successfully exploiting new ideas."),
 ("E","Innovation","Which is a type of innovation?",
  ["Product innovation","Market copying","Price matching","Staff reduction"],0,"Product innovation is a key type."),
 ("E","Innovation","Which is a type of innovation?",
  ["Process innovation","Ignoring customers","Cutting quality","Reducing pay"],0,"Process innovation improves how things are made."),
 ("E","Enterprise","'Blue sky' thinking means:",
  ["Thinking within strict limits","Thinking without restrictions","Copying others","Avoiding ideas"],1,"Blue sky thinking approaches ideas with no restrictions."),
 ("E","Enterprise","Lateral thinking is:",
  ["Step-by-step logic only","Approaching problems from new angles","Avoiding problems","Following rules"],1,"Lateral thinking uses unconventional angles."),
 ("E","Enterprise","Serendipity in enterprise means:",
  ["Careful planning","Discovering opportunities by chance","Avoiding risk","Formal research"],1,"Serendipity = finding opportunities by chance."),
 ("E","Benefits","Which is a benefit of innovation?",
  ["Higher costs","Unique selling points","Fewer customers","Slower production"],1,"Innovation creates USPs."),
 ("E","Benefits","Which is a benefit of innovation?",
  ["New markets","Less competition","Lower reputation","More debt"],0,"Innovation can open new and niche markets."),
 ("E","Risks","Which is a risk of innovation?",
  ["Guaranteed profit","Failing to achieve a return on investment","No resistance","Instant success"],1,"Innovation risks failing to achieve ROI."),
 ("E","Risks","Which is a risk of innovation?",
  ["Resistance to change","Unlimited support","Zero cost","Guaranteed demand"],0,"Resistance to change is a common risk."),
 ("E","Risks","How can resistance to change be reduced?",
  ["Hide the change","Communicate benefits and involve staff","Ignore employees","Cut all training"],1,"Communication and involvement reduce resistance."),
]

# ===================== UNIT 2 =====================
U2 = [
 ("A","Role of marketing","Marketing that anticipates, recognises, stimulates and satisfies demand describes:",
  ["The role of marketing","Market research","The marketing mix","Pricing strategy"],0,"Marketing's principles are anticipating, recognising, stimulating and satisfying demand."),
 ("A","Marketing aims","Which is a marketing aim?",
  ["Increasing market share","Reducing all sales","Ignoring customers","Cutting brand awareness"],0,"Increasing market share is a marketing aim."),
 ("A","Marketing aims","Which is a marketing aim?",
  ["Developing new products","Reducing quality","Avoiding promotion","Cutting the brand"],0,"Developing new products is a marketing aim."),
 ("A","Market types","A small, specialised segment of a market is called a:",
  ["Mass market","Niche market","Global market","Free market"],1,"A niche market is a small, specialised segment."),
 ("A","Market types","A mass market is:",
  ["A large, broad market","A tiny segment","One customer","A monopoly"],0,"A mass market is large and broad."),
 ("A","Segmentation","Segmenting a market by age and income is:",
  ["Demographic segmentation","Geographic segmentation","Behavioural segmentation","Psychographic segmentation"],0,"Age and income are demographic factors."),
 ("A","Segmentation","Segmenting by lifestyle and values is:",
  ["Demographic","Geographic","Psychographic","Behavioural"],2,"Lifestyle and values are psychographic."),
 ("A","Segmentation","Segmenting by region or country is:",
  ["Demographic","Geographic","Psychographic","Behavioural"],1,"Location is geographic segmentation."),
 ("A","Branding","A unique selling point (USP) is:",
  ["A feature that makes a product stand out","A discount","A tax","A distribution channel"],0,"A USP differentiates a product from competitors."),
 ("A","Branding","Brand personality refers to:",
  ["The CEO's name","Human characteristics associated with a brand","The logo size","The price"],1,"Brand personality is the human traits of a brand."),
 ("A","Branding","Brand image is:",
  ["How customers perceive the brand","The legal name","The factory","The supplier"],0,"Brand image is customer perception."),
 ("A","Influences","The size of a business is which type of marketing influence?",
  ["Internal","External","Legal","Economic"],0,"Business size is an internal influence."),
 ("A","Influences","Technological change is which type of marketing influence?",
  ["Internal","External","Personal","Cultural only"],1,"Technology is an external influence."),
 ("A","Influences","The cost of a campaign is which type of influence?",
  ["Internal","External","Social","Legal"],0,"Campaign cost is internal."),
 ("A","Influences","Which is an external influence on marketing?",
  ["Staff expertise","Economic conditions","Business size","Company culture"],1,"Economic conditions are external."),
 # B — research
 ("B","Research purpose","Which is a purpose of market research?",
  ["Identifying target markets","Increasing taxes","Reducing sales","Hiding competitors"],0,"Identifying target markets is a key purpose."),
 ("B","Primary research","Which is a primary research method?",
  ["Government statistics","A customer survey","Trade journal","Old reports"],1,"A survey is primary research."),
 ("B","Primary research","Which is a primary research method?",
  ["Focus group","Census data","Media articles","Published reports"],0,"Focus groups are primary research."),
 ("B","Primary research","Which is a primary research method?",
  ["Observation","Trade journals","Sales records of others","Government data"],0,"Observation is primary research."),
 ("B","Secondary research","Which is a source of secondary research?",
  ["A new questionnaire","Government statistics","A focus group","An interview"],1,"Government statistics are secondary."),
 ("B","Secondary research","Which is an internal source of secondary data?",
  ["Sales records","Government report","Trade journal","Media article"],0,"Sales records are internal secondary data."),
 ("B","Secondary research","Which is an external source of secondary data?",
  ["Loyalty card data","A commercially published report","Internal sales records","Own database"],1,"Commercial reports are external secondary data."),
 ("B","Data types","Quantitative data is:",
  ["Numerical","Descriptive opinions","Only words","Only images"],0,"Quantitative data is numerical."),
 ("B","Data types","Qualitative data is:",
  ["Numerical","Descriptive, non-numerical","Only statistics","Only prices"],1,"Qualitative data is descriptive."),
 ("B","Validity","Valid research:",
  ["Measures what it claims to measure","Is always wrong","Is never repeated","Ignores the topic"],0,"Validity = measures what it claims."),
 ("B","Validity","Reliable research:",
  ["Gives consistent results when repeated","Changes every time","Is never repeated","Ignores the sample"],0,"Reliability = consistent results."),
 ("B","PLC","In which product life cycle stage do sales grow fastest?",
  ["Introduction","Growth","Maturity","Decline"],1,"Sales rise rapidly in growth."),
 ("B","PLC","In which stage is competition most intense?",
  ["Introduction","Growth","Maturity","Decline"],2,"Competition peaks at maturity."),
 ("B","PLC","In which stage do sales fall?",
  ["Introduction","Growth","Maturity","Decline"],3,"Sales fall in decline."),
 ("B","PLC","Heavy promotional spending occurs mainly at:",
  ["Introduction","Maturity","Decline","None"],0,"Introduction needs heavy promotion to build awareness."),
 # C — planning & mix
 ("C","Pricing","Which pricing strategy sets a low initial price?",
  ["Penetration pricing","Price skimming","Cost-plus","Competitor-based"],0,"Penetration pricing = low initial price."),
 ("C","Pricing","Which pricing strategy sets a high initial price?",
  ["Penetration pricing","Price skimming","Cost-plus","Competitor-based"],1,"Skimming = high initial price for early adopters."),
 ("C","Pricing","Cost-plus pricing means:",
  ["Adding a mark-up to cost","Matching competitors","Setting random prices","Ignoring costs"],0,"Cost-plus adds a mark-up to cost."),
 ("C","Pricing","Competitor-based pricing means:",
  ["Adding a mark-up","Setting prices based on competitors","Ignoring rivals","Charging cost only"],1,"Competitor-based pricing follows rivals' prices."),
 ("C","Marketing mix","The 4Ps of the marketing mix are:",
  ["Product, Price, Place, Promotion","People, Price, Place, Profit","Product, Profit, Place, Process","Plan, Price, Place, Promotion"],0,"The 4Ps are Product, Price, Place, Promotion."),
 ("C","Marketing mix","The 'Place' element refers to:",
  ["Distribution","Advertising","Pricing","Product design"],0,"Place = distribution channels."),
 ("C","Marketing mix","The 'Promotion' element refers to:",
  ["Communicating the product","Manufacturing","Pricing","Storage"],0,"Promotion = communicating and persuading."),
 ("C","Extended mix","Which is part of the extended marketing mix (7Ps)?",
  ["People","Profit","Plan","Policy"],0,"People is one of the 3 extra Ps."),
 ("C","Extended mix","Which is part of the extended marketing mix?",
  ["Process","Power","Price only","Place only"],0,"Process is part of the 7Ps."),
 ("C","Extended mix","Which is part of the extended marketing mix?",
  ["Physical environment","Profit","Plan","Policy"],0,"Physical environment is part of the 7Ps."),
 ("C","Promotion","Which is a promotional method?",
  ["Advertising","Manufacturing","Storage","Accounting"],0,"Advertising is promotion."),
 ("C","Promotion","Public relations (PR) is:",
  ["Managing the brand's public image","Paying for ads","Manufacturing","Distribution"],0,"PR manages public image/media coverage."),
 ("C","Promotion","Sponsorship is:",
  ["Paying to associate with an event or team","Selling shares","Hiring staff","Setting prices"],0,"Sponsorship links a brand to an event/team."),
 ("C","Promotion","Social media marketing is popular because it is:",
  ["Cheap and targeted","Always free of risk","Unmeasurable","Only for TV"],0,"Social media is low-cost and targeted."),
 ("C","Place","E-commerce is:",
  ["Selling online","Selling only in shops","Manufacturing","Pricing"],0,"E-commerce is selling online."),
 ("C","Place","Selling through retailers:",
  ["Reaches more customers","Gives full margin to producer","Avoids all intermediaries","Uses no distribution"],0,"Retailers provide wide reach."),
 ("C","Campaign","A campaign message should be:",
  ["Clear and memorable","Confusing","Hidden","Irrelevant"],0,"Messages must be clear and memorable."),
 ("C","Campaign","A campaign budget is allocated based on:",
  ["Objectives and target audience","Random choice","Highest cost only","Lowest cost only"],0,"Budget is allocated to best reach the audience."),
 ("C","Campaign","A campaign timeline:",
  ["Schedules activities with dates","Ignores deadlines","Has no dates","Avoids planning"],0,"A timeline schedules activities."),
 ("C","Appropriateness","Why must a campaign be appropriate for its target market?",
  ["To engage and persuade them","To waste budget","To confuse them","To reach nobody"],0,"Appropriateness ensures the campaign reaches and persuades the audience."),
 # D — campaign development & evaluation
 ("D","Legal","Why must advertising be truthful?",
  ["To protect consumers and avoid fines","To waste money","To mislead","To confuse"],0,"Truthful ads protect consumers and avoid penalties."),
 ("D","Legal","Data protection law requires businesses to:",
  ["Obtain consent before using personal data","Sell all data","Ignore privacy","Share data freely"],0,"Consent is required for using personal data."),
 ("D","Legal","'Greenwashing' means:",
  ["Making misleading environmental claims","Reducing emissions","Recycling","Being honest"],0,"Greenwashing = false eco-claims."),
 ("D","Legal","Which is an ethical consideration in marketing?",
  ["Not targeting children inappropriately","Misleading customers","Ignoring privacy","False claims"],0,"Not exploiting children is ethical."),
 ("D","Evaluation","Which measures a campaign's success?",
  ["Sales increase","Random noise","Time of day","Weather"],0,"Sales increase is a measure."),
 ("D","Evaluation","Return on investment (ROI) measures:",
  ["Profit relative to cost","Only costs","Only revenue","Staff numbers"],0,"ROI = profit relative to campaign cost."),
 ("D","Evaluation","Why should a campaign be evaluated?",
  ["To measure results and learn","To waste time","To ignore outcomes","To avoid learning"],0,"Evaluation measures results and informs future campaigns."),
 ("D","Flexibility","Why should a campaign be flexible?",
  ["To adapt to changes","To stay rigid","To avoid change","To never adjust"],0,"Flexibility allows adaptation to change."),
 # extra C coverage
 ("C","Pricing","A business launching a new innovative product with little competition might use:",
  ["Price skimming","Penetration pricing","Cost-plus only","Competitor matching only"],0,"Skimming suits innovative products."),
 ("C","Pricing","A business entering a competitive market to gain share quickly might use:",
  ["Price skimming","Penetration pricing","High pricing","Monopoly pricing"],1,"Penetration pricing gains share fast."),
 ("C","Promotion","Guerrilla marketing is:",
  ["Low-cost, unconventional tactics","Expensive TV ads","Ignoring promotion","Manufacturing"],0,"Guerrilla marketing is low-cost and unconventional."),
 ("C","Promotion","Personal selling is:",
  ["One-to-one selling","Mass advertising","Online only","Ignoring customers"],0,"Personal selling is direct one-to-one."),
 ("C","Promotion","Product placement is:",
  ["Featuring a product in media content","A discount","Manufacturing","Pricing"],0,"Product placement features products in media."),
 ("C","Campaign","SMART objectives for a campaign are important because they:",
  ["Are measurable and clear","Are vague","Cannot be tracked","Waste resources"],0,"SMART objectives are measurable."),
 ("C","SWOT","In SWOT, a new competitor entering the market is a:",
  ["Strength","Weakness","Opportunity","Threat"],3,"A new competitor is a threat."),
 ("C","SWOT","In SWOT, a strong brand would be a:",
  ["Strength","Weakness","Opportunity","Threat"],0,"A strong brand is an internal strength."),
]

# ===================== UNIT 3 =====================
U3 = [
 ("A","Products","Which financial product is used for day-to-day transactions?",
  ["Savings account","Current account","Premium bond","ISA"],1,"A current account is for everyday money management."),
 ("A","Products","An ISA is attractive because:",
  ["Interest and gains are tax-free","It guarantees profit","It has no limits","It is risk-free"],0,"ISA interest/gains are tax-free."),
 ("A","Borrowing","Which is typically the most expensive form of borrowing?",
  ["Personal loan","Payday loan","Mortgage","Overdraft at low rate"],1,"Payday loans have very high interest rates."),
 ("A","Borrowing","An overdraft is:",
  ["Spending beyond your account balance up to a limit","A fixed loan","A share","An ISA"],0,"An overdraft allows spending below zero to a limit."),
 ("A","Borrowing","A mortgage is secured against:",
  ["Property","Your salary","A car","Shares"],0,"A mortgage is secured against property."),
 ("A","Insurance","Insurance protects by:",
  ["Transferring risk to the insurer for a premium","Removing all risk for free","Guaranteeing profit","Increasing risk"],0,"Insurance transfers risk for a premium."),
 ("A","Budgeting","Non-discretionary spending is:",
  ["Essential spending (rent, food)","Optional spending","Luxury spending","Gambling"],0,"Non-discretionary is essential."),
 ("A","Budgeting","Discretionary spending is:",
  ["Essential","Optional and non-essential","Unavoidable","Tax"],1,"Discretionary spending is optional."),
 ("A","Budgeting","A budget deficit means:",
  ["Expenditure exceeds income","Income exceeds expenditure","Balanced","Profit"],0,"Deficit = spending exceeds income."),
 # B — institutions
 ("B","Institutions","A building society is:",
  ["A mutual owned by its members","Shareholder-owned only","A government body","A credit card firm"],0,"Building societies are member-owned mutuals."),
 ("B","Institutions","A credit union is:",
  ["A not-for-profit cooperative","A retail bank","An investment bank","A payday lender"],0,"Credit unions are not-for-profit cooperatives."),
 ("B","Institutions","The UK's central bank is:",
  ["The Bank of England","A retail bank","A building society","A credit union"],0,"The Bank of England is the central bank."),
 ("B","Communication","Which is a banking communication method?",
  ["Internet banking","Cooking","Driving","Manufacturing"],0,"Internet banking is a communication channel."),
 ("B","Communication","A disadvantage of internet banking is:",
  ["Security risks","It is always free","No skills needed","Unlimited cash"],0,"Internet banking carries security risks."),
 ("B","Communication","An advantage of branch banking is:",
  ["Face-to-face advice","Only for the young","No human help","Always closed"],0,"Branches offer personal advice."),
]
# wait — U3 needs only to reach 100; it already has 86, so 14 new. Above has 16; trim below.

# ===================== UNIT 4 =====================
U4 = [
 ("A","Role","Which is a task of an event organiser?",
  ["Planning","Manufacturing","Mining","Farming"],0,"Planning is a core event organiser task."),
 ("A","Role","Which is a task of an event organiser?",
  ["Budgeting","Driving a bus","Cooking","Teaching"],0,"Budgeting is a core event organiser task."),
 ("A","Role","Which stage comes after the event has run?",
  ["Evaluation","Feasibility","Planning","Staging"],0,"Evaluation follows the event."),
 ("A","Skills","Which skill is essential for an event organiser?",
  ["Communication","Sleeping","Ignoring","Avoiding people"],0,"Communication is essential."),
 ("A","Skills","Which skill helps an event organiser get good prices from suppliers?",
  ["Negotiation","Cooking","Driving","Swimming"],0,"Negotiation secures good prices and terms."),
 ("A","Skills","Which skill helps an event organiser motivate volunteers?",
  ["Leadership","Mining","Farming","Typing"],0,"Leadership motivates and directs teams."),
 ("A","Skills","Which skill helps meet deadlines?",
  ["Time management","Procrastination","Avoiding work","Ignoring schedules"],0,"Time management helps meet deadlines."),
 ("A","Skills audit","A skills audit identifies:",
  ["Strengths and areas for development","Only weaknesses","Only strengths","Nothing"],0,"A skills audit reviews strengths and gaps."),
 ("A","Skills audit","Why carry out a skills audit before an event?",
  ["To identify skills gaps and plan development","To waste time","To ignore skills","To avoid planning"],0,"It identifies gaps to address."),
 # B — feasibility
 ("B","Types","A wedding is which type of event?",
  ["Social","Business","Sports","None"],0,"A wedding is a social event."),
 ("B","Types","A conference is which type of event?",
  ["Business","Social","Sports","Entertainment only"],0,"A conference is a business event."),
 ("B","Types","A tournament is which type of event?",
  ["Sports","Business","Social","None"],0,"A tournament is a sports event."),
 ("B","Types","A concert is which type of event?",
  ["Entertainment","Business","Social","Sports only"],0,"A concert is an entertainment event."),
 ("B","Success","Which factor affects event success?",
  ["Venue","Hair colour","Random","Nothing"],0,"The venue affects success."),
 ("B","Success","Which factor affects event success?",
  ["Timing","Weather underwater","Nothing","Noise only"],0,"Timing affects attendance and success."),
 ("B","Success","Which is a critical success factor?",
  ["Clear aims and objectives","Confusion","No budget","Poor planning"],0,"Clear aims are a critical success factor."),
 ("B","Feasibility","Feasibility means:",
  ["Whether the event is practical and achievable","Whether it is expensive","Whether it is fun","Whether it is big"],0,"Feasibility = practical and achievable."),
 ("B","Feasibility","Which factor is considered in feasibility?",
  ["Cost and budget","Colour of banners","Music style","Food taste"],0,"Cost and budget are key feasibility factors."),
 ("B","Feasibility","Which factor is considered in feasibility?",
  ["Availability of resources","The organiser's height","The weather forecast only","Nothing"],0,"Resource availability affects feasibility."),
 # C — planning
 ("C","Planning tool","Which planning tool shows tasks against a timeline?",
  ["Gantt chart","A pen","A calculator","A map"],0,"A Gantt chart shows tasks against time."),
 ("C","Planning tool","Which planning tool lists tasks, owners and deadlines?",
  ["Action plan","A diary only","A photo","A logo"],0,"An action plan lists tasks, owners and deadlines."),
 ("C","Planning tool","Critical path analysis identifies:",
  ["Tasks that determine the event's duration","Random tasks","Only costs","Only colours"],0,"CPA finds the critical tasks/duration."),
 ("C","Planning tool","A checklist helps by:",
  ["Ensuring nothing is forgotten","Adding confusion","Hiding tasks","Wasting time"],0,"Checklists prevent oversights."),
 ("C","Budget","Which is an event budget cost?",
  ["Venue hire","Free air","Nothing","Happy thoughts"],0,"Venue hire is a budget cost."),
 ("C","Budget","Which is an event budget cost?",
  ["Marketing","Sunlight","Happiness","Nothing"],0,"Marketing is a budget cost."),
 ("C","Health & safety","A risk assessment identifies:",
  ["Hazards and controls","Only profits","Only colours","Nothing"],0,"Risk assessments identify hazards and controls."),
 ("C","Health & safety","Why is a risk assessment important?",
  ["To protect people and comply with law","To waste time","To add danger","To ignore safety"],0,"It protects people and ensures compliance."),
 ("C","Contingency","A contingency plan prepares for:",
  ["Unexpected problems","Nothing","Only profits","Success only"],0,"Contingency plans prepare for problems."),
 ("C","Contingency","Why have a contingency plan for an outdoor event?",
  ["To handle bad weather","To enjoy sunshine","To ignore weather","To waste money"],0,"Outdoor events need weather contingencies."),
 ("C","Planning","Which is a factor to consider when planning an event?",
  ["Insurance","Hair colour","Random","Nothing"],0,"Insurance is an important planning factor."),
 ("C","Planning","Which is a factor to consider when planning an event?",
  ["Accessibility","Nothing","Random","Colour of chairs"],0,"Accessibility is a planning factor."),
 # D — staging & managing
 ("D","Managing","An event manager's on-the-day responsibility is:",
  ["Coordinating staff","Sleeping","Avoiding work","Leaving early"],0,"Coordinating staff is key on the day."),
 ("D","Managing","An event manager's responsibility is:",
  ["Overseeing the schedule","Ignoring time","Avoiding staff","Cancelling"],0,"Overseeing the schedule is key."),
 ("D","Managing","An event manager's responsibility is:",
  ["Ensuring health and safety","Ignoring hazards","Avoiding safety","Causing risk"],0,"Ensuring health and safety is essential."),
 ("D","Problem solving","When a problem arises, the event manager should first:",
  ["Assess the problem and its impact","Panic","Ignore it","Blame others"],0,"Assess first, then act."),
 ("D","Problem solving","Staying calm when a problem occurs helps because:",
  ["It allows clear thinking","It makes things worse","It causes panic","It helps no one"],0,"Calm allows rational decisions."),
 ("D","Problem solving","A contingency plan helps problem solving by:",
  ["Providing pre-agreed responses","Adding confusion","Slowing response","Creating problems"],0,"Contingency plans enable quick responses."),
 ("D","Staging","Staging an event means:",
  ["Running the event on the day","Planning only","Buying tickets","Writing reports"],0,"Staging is running the event on the day."),
 ("D","Staging","Why is a clear schedule important on the day?",
  ["It keeps activities on time","It confuses staff","It wastes time","It does nothing"],0,"A schedule keeps the event on track."),
 ("D","Staging","Why is venue layout important?",
  ["It improves experience and safety","It is irrelevant","It wastes space","It confuses"],0,"Layout improves experience and safety."),
 # E — evaluation
 ("E","Evaluation","Which is a way to evaluate an event?",
  ["Feedback from attendees","Ignoring everyone","Guessing","Doing nothing"],0,"Feedback evaluates the event."),
 ("E","Evaluation","Which is a way to evaluate an event?",
  ["Review against objectives","Ignoring goals","Random guessing","Nothing"],0,"Reviewing against objectives evaluates."),
 ("E","Evaluation","Which is a way to evaluate an event?",
  ["Budget analysis","Ignoring money","Guessing","Nothing"],0,"Budget analysis evaluates financial success."),
 ("E","Evaluation","Why evaluate an event?",
  ["To learn and improve","To waste time","To ignore outcomes","To avoid learning"],0,"Evaluation drives improvement."),
 ("E","Skills","Running an event develops which skill?",
  ["Communication","Nothing","Sleeping","Ignoring"],0,"Events develop communication."),
 ("E","Skills","Running an event develops which skill?",
  ["Leadership","Nothing","Avoiding","Guessing"],0,"Events develop leadership."),
 ("E","Skills","Running an event develops which skill?",
  ["Problem solving","Nothing","Ignoring","Guessing"],0,"Events develop problem solving."),
 ("E","Reflection","Reflection converts experience into:",
  ["Learning","Confusion","Waste","Nothing"],0,"Reflection turns experience into learning."),
 ("E","Reflection","Why reflect after an event?",
  ["To identify strengths and areas to improve","To ignore everything","To waste time","To forget"],0,"Reflection identifies strengths and improvements."),
 ("E","Reflection","Setting development goals should be:",
  ["SMART (specific, measurable, etc.)","Vague","Impossible","Random"],0,"Development goals should be SMART."),
]

def expand(unit, items):
    data = load(unit)
    n = next_num(data)
    for it in items:
        n += 1
        data.append(mcq(n, *it))
    save(unit, data)
    return len(data)

print("unit-1:", expand("unit-1", U1))
print("unit-2:", expand("unit-2", U2))
print("unit-3:", expand("unit-3", U3))
print("unit-4:", expand("unit-4", U4))