# -*- coding: utf-8 -*-
"""Regenerate AAQ IT Unit 2 aim_C.json (Cyber security documentation) and
aim_D.json (Forensic procedures) to match the exact spec (Issue 5, Nov 2025)."""

import json

def q(i, aim, topic, verb, marks, ao, question, points, add=None):
    return {"id": "%s%03d" % (aim, i), "learning_aim": aim, "topic": topic,
            "command_verb": verb, "marks": marks, "ao": ao, "question": question,
            "type": "short", "mark_scheme": {"instruction": "Award marks as indicated.",
            "points": points, "additional_guidance": add}}

C = [
 q(1,"C","C1.1 Cyber security policy","State",2,"AO1",
   "State the four stages of the Plan-Do-Check-Act loop used in a cyber security policy.",
   ["Plan (1)","Do (1)","Check (1)","Act (1)"], "Accept in correct order or any order."),
 q(2,"C","C1.1 Cyber security policy","Explain",4,"AO2",
   "Explain why a cyber security policy should follow a Plan-Do-Check-Act approach rather than being a one-off document.",
   ["Plan: identify security objectives and risks before acting (1)","Do: implement the security controls (1)","Check: monitor and audit whether the controls are working (1)","Act: take corrective action and continually improve — security is an ongoing process, not a single event (1)"]),
 q(3,"C","C1.1 Internet and email use","State",2,"AO1",
   "State two rules that are typically included in an internet and email use policy.",
   ["Not sending confidential information by email (1)","Not visiting potentially dangerous websites (1)","Not downloading executable files (1)","Not uploading/downloading copyrighted material (1)","Not viewing inappropriate, offensive or illegal material (1)"], "Award 1 mark each, up to 2."),
 q(4,"C","C1.1 Security and password procedures","Describe",3,"AO1",
   "Describe three measures that an organisation's password policy should specify.",
   ["Minimum and maximum length for passwords (1)","Character restrictions (e.g. require upper/lower case, numbers, symbols) (1)","A deny list of common/weak passwords (1)","Lockout after failed login attempts or inactivity (1)","Preventing password sharing or multiple logons with the same password (1)"], "Award 1 mark each, up to 3."),
 q(5,"C","C1.1 Staff responsibilities","Explain",4,"AO2",
   "Explain the responsibilities staff have in maintaining cyber security.",
   ["Complete required security training (1)","Follow security procedures and report problems (1)","Respond to and report suspicious activity (1)","Maintain security in their own workspace and behaviour (1)"]),
 q(6,"C","C1.1 Staff training","Explain",4,"AO2",
   "Explain how an organisation should deliver effective staff IT security training.",
   ["Leadership must ensure training is funded and resourced (1)","Training should be flexible so everyone can take part (1)","Use a range of resources and learning styles (1)","Track progress and use incentives rather than punishment (1)","Provide ongoing training to reinforce and cover new threats (1)"]),
 q(7,"C","C1.2 Security audits","Explain",4,"AO2",
   "Explain the purpose of a security audit and how it is carried out.",
   ["An audit checks compliance against internal policies and external regulations/laws (1)","It starts by defining audit goals and scope (1)","It identifies problems, gaps and weaknesses (1)","It reports results and any required improvements/changes (1)"]),
 q(8,"C","C1.3 Backup policy","State",2,"AO1",
   "State two factors that a backup policy should specify.",
   ["Selection of data to be backed up (1)","Backup methods and type (full/differential/incremental) (1)","Frequency/scheduling (1)","Storage strategy (onsite/offsite/cloud) (1)","A backup testing strategy (1)","Legal/regulatory compliance (1)"], "Award 1 mark each, up to 2."),
 q(9,"C","C1.3 Backup policy","Explain",4,"AO2",
   "Explain why a backup policy must include a testing strategy.",
   ["Backups may be corrupted or incomplete without the organisation knowing (1)","Testing confirms that data can actually be restored when needed (1)","A backup that cannot be restored is worthless in a disaster (1)","Regular testing identifies problems before a real incident occurs (1)"]),
 q(10,"C","C1.4 Data protection policy","Explain",4,"AO2",
   "Explain the role of the Data Protection Officer (DPO) and the content of a data protection policy.",
   ["The DPO oversees compliance with data protection principles and protects rights/privacy (1)","The policy ensures staff training and system security procedures are in place (1)","It applies to external contractors, consultants and vendors too (1)","It sets out the responsibility and accountability of staff and the organisation (1)"]),
 q(11,"C","C1.5 Incident response policy","State",2,"AO1",
   "State two contacts that must be listed in a cyber security incident response policy.",
   ["Incident response team leader/provider (1)","IT team leader/provider (1)","Senior management (1)","Legal (1)","Public relations (1)","Human resources (1)","Insurance (1)"], "Award 1 mark each, up to 2."),
 q(12,"C","C1.5 Incident response policy","Explain",4,"AO2",
   "Explain what procedures and flowcharts an incident response policy should include.",
   ["Triage — initial decisions, escalation (1)","Main response — analysis, containment, mitigation, recovery (1)","Reviewing, reporting and closing the incident (1)","Communications — a contact telephone plus alternative/backup and a conference call facility (1)"]),
 q(13,"C","C1.6 Disaster recovery policy","Explain",4,"AO2",
   "Explain the purpose of a disaster recovery policy and its key content.",
   ["Its purpose is to define how the organisation recovers from a major disruption (1)","It includes triage — a list of possible events, their severity and the appropriate response (1)","It sets out roles, responsibilities and contact lists (1)","It includes monitoring and reporting requirements (1)"]),
 q(14,"C","C1.6 Disaster recovery policy","State",2,"AO1",
   "State the three plans that disaster recovery triage may activate.",
   ["Activate the cyber security incident response plan (1)","Activate the business continuity plan (1)","Activate the disaster recovery plan (1)"]),
 q(15,"C","C1.7 External services policy","Explain",4,"AO2",
   "Explain what an external services policy should cover when an organisation uses cloud services.",
   ["Cloud resources requiring protection (1)","Acceptable use of the cloud service (1)","Data protection requirements (1)","Authorisation and access control; management, responsibility and accountability (1)","Incident response procedures and regulatory compliance (1)"]),
 q(16,"C","C1.7 External services policy","Describe",3,"AO1",
   "Describe how an external services policy applies to software and hardware vendors.",
   ["Sources, vendors, contractors and other third parties must be approved (1)","Service agreements and licensing must be defined (1)","Maintenance, support and escalation procedures must be set out (1)"], "Award 1 mark each, up to 3."),
]

D = [
 q(1,"D","D1.1 Meeting requirements for forensics","State",2,"AO1",
   "State two actions to preserve a seized mobile device for forensic analysis.",
   ["Retain the current power state/status if possible (1)","Isolate the device from the network/communications (1)","Keep chargers and cables with the device (1)","Use a Faraday bag/cage or disable wireless communication (1)","Document the chain of custody (1)"], "Award 1 mark each, up to 2."),
 q(2,"D","D1.1 Meeting requirements for forensics","Explain",4,"AO2",
   "Explain how an investigator should isolate a device that is suspected of communicating so that evidence is preserved.",
   ["Photograph the screen first to capture what is displayed (1)","Turn off the device or remove the battery/power cable (1)","Use airplane mode or disable wireless communication (1)","Place the device in a Faraday bag/cage to block signals (1)"]),
 q(3,"D","D1.1 Meeting requirements for forensics","Explain",4,"AO2",
   "Explain the importance of documenting the chain of custody when collecting forensic evidence.",
   ["The chain of custody records everyone who handled the evidence, when and what they did (1)","It proves the evidence has not been altered or tampered with (1)","An unbroken chain is required for evidence to be admissible in court (1)","Any gap or inconsistency can make the evidence inadmissible (1)"]),
 q(4,"D","D1.1 Challenges of live forensics","Explain",4,"AO2",
   "Explain two challenges of performing live forensics on a running system.",
   ["Data is changing in situ — files and memory are being modified while examined (1)","Recovering corrupted data and preventing further corruption is difficult (1)","Capturing data in active memory must be done quickly before it is lost (1)","Remote data must be captured over the network, and temporary files must not be lost (1)"]),
 q(5,"D","D1.1 Network forensics","Explain",4,"AO2",
   "Explain the steps required before scanning a network for forensic analysis.",
   ["Agree a network-testing forensics methodology with supervisory and investigatory authorities (1)","Ensure permission is granted to carry out the scan (1)","Ensure the testing protocol will not disrupt a live system (1)","Use passive and active analysis tools appropriately (1)"]),
 q(6,"D","D1.1 Network forensics","Describe",3,"AO1",
   "Describe the network infrastructure that an investigator would review during network forensics.",
   ["Firewalls and infrastructure devices — switches, routers, wireless access points (1)","Client or server logs (1)","Malware activity and alerts (1)"], "Award 1 mark each, up to 3."),
 q(7,"D","D1.1 Documenting the scene","Describe",3,"AO1",
   "Describe how an investigator documents the scene of an incident.",
   ["Prior planning for a range of scenarios (1)","Securing the scene (1)","Plans, photos and diagrams of the scene (1)","Contemporaneous notes (1)","Witness statements (1)"], "Award 1 mark each, up to 3."),
 q(8,"D","D2.1 Retaining snapshots","Explain",4,"AO2",
   "Explain why a hash/checksum is generated for a forensic copy of a system.",
   ["A hash (checksum) is a digital fingerprint of the data (1)","It proves the forensic copy is an exact match of the original (1)","If the hash changes, it shows the data has been altered (1)","This maintains evidence integrity and admissibility (1)"]),
 q(9,"D","D2.1 Recording findings","State",2,"AO1",
   "State two requirements for recording forensic findings reliably.",
   ["No action should change the data on the digital device (1)","Collection must be done by a competent person (1)","A trail/record of all actions taken must be created (1)","Documentation of who is responsible for collection/decisions (1)"], "Award 1 mark each, up to 2."),
 q(10,"D","D2.1 Recording alterations","Explain",4,"AO2",
   "Explain why an investigator should work with copies/images rather than original data.",
   ["Working on the original could alter the evidence (1)","Altered data may be inadmissible in court (1)","Using copies preserves the original unchanged (1)","All alterations (intentional or unintentional) must be documented (1)"]),
 q(11,"D","D2.1 Visual evidence","State",2,"AO1",
   "State two forms of visual evidence created during forensic analysis.",
   ["Photos (1)","Videos (1)","Screenshots (1)","Date-time stamps and metadata (1)"], "Award 1 mark each, up to 2."),
 q(12,"D","D2.1 False positives","Explain",4,"AO2",
   "Explain how an investigator ensures findings are relevant and not false positives.",
   ["Define file signatures and search criteria carefully (1)","Know the error rates of the tools and data types used (1)","Feed back false-positive data to improve the detection method (1)","Manually review all positives and further investigate filtered positives (1)"]),
 q(13,"D","D2.2 Assessing findings","State",2,"AO1",
   "State two things an investigator assesses findings for.",
   ["Evidence of a crime and/or an incident (1)","A regulatory breach (1)","Civil liability or contractual breach (1)","Non-compliance with internal policy (1)","Negligence or mismanagement (1)"], "Award 1 mark each, up to 2."),
 q(14,"D","D2.2 Compromise indicators","Describe",3,"AO1",
   "Describe three indicators that a system has been compromised.",
   ["Unusual traffic — inbound, outbound or from unusual geographical regions (1)","Unusual login attempts or DNS requests (1)","Increase in file/data reads or requests (1)","Unusual port usage (1)","Suspicious changes to or access to files/data (1)"], "Award 1 mark each, up to 3."),
 q(15,"D","D2.3 Writing security reports","Explain",4,"AO2",
   "Explain the structure and purpose of a security report written after an incident.",
   ["A clear structure — title, contents, introduction, headings, numbered/bulleted points, conclusions, footnotes, citations (1)","It analyses the incident to identify errors/omissions in procedures (1)","It identifies errors/delays in detection and remedial actions (1)","It recommends improvements to IT policies and protection measures (physical, software, hardware, processes, training) (1)"]),
 q(16,"D","D2.3 Writing security reports","State",2,"AO1",
   "State two areas of improvement a security report should recommend.",
   ["Improvements to the content of IT policies (1)","Improvements to physical security measures (1)","Improvements to software or hardware protection (1)","Improvements to processes, procedures and training (1)"], "Award 1 mark each, up to 2."),
]

with open("revision/btec/level-3/IT-AAQ/unit-2/data/aim_C.json", "w", encoding="utf-8") as f:
    json.dump(C, f, ensure_ascii=False, indent=1)
with open("revision/btec/level-3/IT-AAQ/unit-2/data/aim_D.json", "w", encoding="utf-8") as f:
    json.dump(D, f, ensure_ascii=False, indent=1)

print("aim_C:", len(C), "aim_D:", len(D))